apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: project.yaml
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: sso71-mysql-persistent
      application: sso
      template: sso71-mysql-persistent
      xpaas: 1.4.7
    name: sso
  spec:
    replicas: 1
    selector:
      deploymentConfig: sso
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: sso
          deploymentConfig: sso
        name: sso
      spec:
        containers:
        - env:
          - name: DB_SERVICE_PREFIX_MAPPING
            value: sso-mysql=DB
          - name: DB_JNDI
            value: java:jboss/datasources/KeycloakDS
          - name: DB_USERNAME
            value: usert0B
          - name: DB_PASSWORD
            value: viiR0aFJ
          - name: DB_DATABASE
            value: root
          - name: TX_DATABASE_PREFIX_MAPPING
            value: sso-mysql=DB
          - name: DB_MIN_POOL_SIZE
          - name: DB_MAX_POOL_SIZE
          - name: DB_TX_ISOLATION
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=sso
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: HTTPS_KEYSTORE_DIR
            value: /etc/sso-secret-volume
          - name: HTTPS_KEYSTORE
            value: sso-https.jks
          - name: HTTPS_KEYSTORE_TYPE
          - name: HTTPS_NAME
          - name: HTTPS_PASSWORD
            value: redhat123
          - name: JGROUPS_ENCRYPT_SECRET
            value: sso-ssl-secret
          - name: JGROUPS_ENCRYPT_KEYSTORE_DIR
            value: /etc/jgroups-encrypt-secret-volume
          - name: JGROUPS_ENCRYPT_KEYSTORE
            value: jgroups.jceks
          - name: JGROUPS_ENCRYPT_NAME
          - name: JGROUPS_ENCRYPT_PASSWORD
            value: redhat123
          - name: JGROUPS_CLUSTER_PASSWORD
            value: redhat123
          - name: SSO_ADMIN_USERNAME
            value: admin
          - name: SSO_ADMIN_PASSWORD
            value: redhat123
          - name: SSO_REALM
            value: 3Scale
          - name: SSO_SERVICE_USERNAME
          - name: SSO_SERVICE_PASSWORD
          - name: SSO_TRUSTSTORE
            value: truststore.jks
          - name: SSO_TRUSTSTORE_DIR
            value: /etc/sso-secret-volume
          - name: SSO_TRUSTSTORE_PASSWORD
            value: redhat123
          image: registry.access.redhat.com/redhat-sso-7/sso71-openshift@sha256:8c8aa52c1dc52cb3fe19ab9df5d129e3dc8bae754fb3a84d5194b445071b0ca8
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /opt/eap/bin/jboss-cli.sh
                - -c
                - :shutdown(timeout=60)
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/livenessProbe.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: sso
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/eap-secret-volume
            name: eap-keystore-volume
            readOnly: true
          - mountPath: /etc/jgroups-encrypt-secret-volume
            name: eap-jgroups-keystore-volume
            readOnly: true
          - mountPath: /etc/sso-secret-volume
            name: sso-truststore-volume
            readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: sso-service-account
        serviceAccountName: sso-service-account
        terminationGracePeriodSeconds: 75
        volumes:
        - name: eap-keystore-volume
          secret:
            defaultMode: 420
            secretName: sso-ssl-secret
        - name: eap-jgroups-keystore-volume
          secret:
            defaultMode: 420
            secretName: sso-ssl-secret
        - name: sso-truststore-volume
          secret:
            defaultMode: 420
            secretName: sso-ssl-secret
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: sso71-mysql-persistent
      application: sso
      template: sso71-mysql-persistent
      xpaas: 1.4.7
    name: sso-mysql
  spec:
    replicas: 1
    selector:
      deploymentConfig: sso-mysql
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: sso
          deploymentConfig: sso-mysql
        name: sso-mysql
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: usert0B
          - name: MYSQL_PASSWORD
            value: viiR0aFJ
          - name: MYSQL_DATABASE
            value: root
          - name: MYSQL_LOWER_CASE_TABLE_NAMES
          - name: MYSQL_MAX_CONNECTIONS
          - name: MYSQL_FT_MIN_WORD_LEN
          - name: MYSQL_FT_MAX_WORD_LEN
          - name: MYSQL_AIO
          image: registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:3abe773161b613b57f653c10ea1019ef7d9a05b2313390a8627be74df98dae77
          imagePullPolicy: Always
          name: sso-mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: sso-mysql-pvol
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 60
        volumes:
        - name: sso-mysql-pvol
          persistentVolumeClaim:
            claimName: sso-mysql-claim
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - sso-mysql
        from:
          kind: ImageStreamTag
          name: mysql:5.7
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's https service.
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: sso71-mysql-persistent
      application: sso
      template: sso71-mysql-persistent
      xpaas: 1.4.7
    name: secure-sso
  spec:
    host: secure-sso-sso.${DOMAIN_NAME_SUFFIX}
    tls:
      termination: passthrough
    to:
      kind: Service
      name: secure-sso
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-02-01T09:54:52Z
        status: "True"
        type: Admitted
      host: secure-sso-sso.${DOMAIN_NAME_SUFFIX}
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: sso71-mysql-persistent
      application: sso
      template: sso71-mysql-persistent
      xpaas: 1.4.7
    name: sso
  spec:
    host: sso-sso.${DOMAIN_NAME_SUFFIX}
    to:
      kind: Service
      name: sso
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-02-01T09:54:51Z
        status: "True"
        type: Admitted
      host: sso-sso.${DOMAIN_NAME_SUFFIX}
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      gluster.kubernetes.io/provisioned-for-pvc: sso-mysql-claim
    name: glusterfs-dynamic-sso-mysql-claim
  spec:
    ports:
    - port: 1
      protocol: TCP
      targetPort: 1
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's https port.
      service.alpha.openshift.io/dependencies: '[{"name": "sso-mysql", "kind": "Service"}]'
    creationTimestamp: null
    labels:
      app: sso71-mysql-persistent
      application: sso
      template: sso71-mysql-persistent
      xpaas: 1.4.7
    name: secure-sso
  spec:
    ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentConfig: sso
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
      service.alpha.openshift.io/dependencies: '[{"name": "sso-mysql", "kind": "Service"}]'
    creationTimestamp: null
    labels:
      app: sso71-mysql-persistent
      application: sso
      template: sso71-mysql-persistent
      xpaas: 1.4.7
    name: sso
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentConfig: sso
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The database server's port.
    creationTimestamp: null
    labels:
      app: sso71-mysql-persistent
      application: sso
      template: sso71-mysql-persistent
      xpaas: 1.4.7
    name: sso-mysql
  spec:
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      deploymentConfig: sso-mysql
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
  - description: Domain name suffix - added to all routes
    displayName: Domain Name Suffix
    name: DOMAIN_NAME_SUFFIX
    value: apps.demolab.local
