apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: sso-mysql-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: ibmc-block-gold
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
