apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: sso-service-account-dockercfg-v2dmf
  kind: ServiceAccount
  metadata:
    creationTimestamp: 2018-02-01T09:37:43Z
    name: sso-service-account
    namespace: sso
    resourceVersion: "241374291"
    selfLink: /api/v1/namespaces/sso/serviceaccounts/sso-service-account
    uid: 8dbf83d5-0733-11e8-b959-52540064f8a5
  secrets:
  - name: sso-service-account-token-c2qc5
  - name: sso-service-account-dockercfg-v2dmf
  - name: sso-jgroup-secret
  - name: sso-ssl-secret
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
