---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sso-mysql-claim
  namespace: sso
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gluster-container
