apiVersion: v1
items:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-28T17:03:26Z
    name: admin
    namespace: fisbuild
    resourceVersion: "374487845"
    selfLink: /oapi/v1/namespaces/fisbuild/rolebindings/admin
    uid: 4ac31e34-1ca9-11e8-a813-5254002f83b4
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: pprosser
  userNames:
  - pprosser
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-28T17:03:26Z
    name: system:deployers
    namespace: fisbuild
    resourceVersion: "374487844"
    selfLink: /oapi/v1/namespaces/fisbuild/rolebindings/system%3Adeployers
    uid: 4ac27d75-1ca9-11e8-a813-5254002f83b4
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: fisbuild
  userNames:
  - system:serviceaccount:fisbuild:deployer
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-28T17:03:26Z
    name: system:image-builders
    namespace: fisbuild
    resourceVersion: "374487843"
    selfLink: /oapi/v1/namespaces/fisbuild/rolebindings/system%3Aimage-builders
    uid: 4ac17d5c-1ca9-11e8-a813-5254002f83b4
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: fisbuild
  userNames:
  - system:serviceaccount:fisbuild:builder
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:fisbuild
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-28T17:03:26Z
    name: system:image-pullers
    namespace: fisbuild
    resourceVersion: "374487841"
    selfLink: /oapi/v1/namespaces/fisbuild/rolebindings/system%3Aimage-pullers
    uid: 4ac08489-1ca9-11e8-a813-5254002f83b4
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:fisbuild
  userNames: null
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
