apiVersion: v1
items:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-07T17:44:09Z
    name: admin
    namespace: fisdemocicd
    resourceVersion: "340122202"
    selfLink: /oapi/v1/namespaces/fisdemocicd/rolebindings/admin
    uid: 8060d88c-0c2e-11e8-8448-52540064f8a5
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: pprosser
  - kind: User
    name: jenkins
  userNames:
  - pprosser
  - jenkins
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2018-02-07T17:44:10Z
    labels:
      app: jenkins-ephemeral
      template: jenkins-ephemeral-template
    name: jenkins_edit
    namespace: fisdemocicd
    resourceVersion: "340122575"
    selfLink: /oapi/v1/namespaces/fisdemocicd/rolebindings/jenkins_edit
    uid: 80bda0f4-0c2e-11e8-8448-52540064f8a5
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
  - kind: ServiceAccount
    name: default
    namespace: fisdemocicd
  - kind: User
    name: mmusaji
  userNames:
  - system:serviceaccount:fisdemocicd:jenkins
  - system:serviceaccount:fisdemocicd:default
  - mmusaji
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-07T17:44:09Z
    name: system:deployers
    namespace: fisdemocicd
    resourceVersion: "260826940"
    selfLink: /oapi/v1/namespaces/fisdemocicd/rolebindings/system%3Adeployers
    uid: 805f2b1d-0c2e-11e8-8448-52540064f8a5
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: fisdemocicd
  userNames:
  - system:serviceaccount:fisdemocicd:deployer
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-07T17:44:09Z
    name: system:image-builders
    namespace: fisdemocicd
    resourceVersion: "260826935"
    selfLink: /oapi/v1/namespaces/fisdemocicd/rolebindings/system%3Aimage-builders
    uid: 805e96ff-0c2e-11e8-8448-52540064f8a5
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: fisdemocicd
  userNames:
  - system:serviceaccount:fisdemocicd:builder
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:fisdemocicd
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-07T17:44:09Z
    name: system:image-pullers
    namespace: fisdemocicd
    resourceVersion: "260826933"
    selfLink: /oapi/v1/namespaces/fisdemocicd/rolebindings/system%3Aimage-pullers
    uid: 805df44d-0c2e-11e8-8448-52540064f8a5
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:fisdemocicd
  userNames: null
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
