---
apiVersion: v1
data:
  address: ""
  authentication: ""
  domain: ""
  openssl.verify.mode: ""
  password: ""
  port: ""
  username: ""
kind: ConfigMap
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  name: smtp
