---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  name: system
  namespace: amp
data:
  rolling_updates.yml: |
    production:
      old_charts: false
      new_provider_documentation: false
      proxy_pro: false
      instant_bill_plan_change: false
      service_permissions: true
      async_apicast_deploy: false
      duplicate_application_id: true
      duplicate_user_key: true
      plan_changes_wizard: false
      require_cc_on_signup: false
      apicast_per_service: true
      new_notification_system: true
      cms_api: false
      apicast_v2: true
      forum: false
      published_service_plan_signup: true
      apicast_oidc: true
  zync.yml: |
    production:
      endpoint: 'http://zync:8080'
      authentication:
        token: "<%= ENV.fetch('ZYNC_AUTHENTICATION_TOKEN') %>"
      connect_timeout: 5
      send_timeout: 5
      receive_timeout: 10
      root_url: 'http://system-provider:3000'
