---
# Documentation:
# This playbook is used to deploy 3Scale, and a restful service
#
- name:               Create 3Scale AMP and deploy members api
  hosts:              localhost
  connection:         local
  gather_facts: no

  vars_prompt:
    - name:           ocp_username
      prompt:         "Please provide Openshift Login username"
      default:        developer
      private:        no
    - name:           ocp_password
      prompt:         "Please provide your Openshift Login password"
      default:        developer
      private:        yes
    - name:           ocp_url
      prompt:         "Please provide your Openshift URL"
      default:        https://192.168.99.100:8443
      private:        no
    - name:           domain_name_suffix
      prompt:         "Please Enter the domain wildcard name suffix for all OCP routes"
      default:        apps.demolab.local
      private:        no
    - name:           keystore_password
      prompt:         "Please enter the default password for keystores"
      default:        redhat123
    - name:           git_repo
      prompt:         "Please Enter the Git repo to clone to get hold of artefacts"
      default:        https://github.com/pprosser-redhat/3scalebackup.git
      private:        no
    - name:           clone_destination
      prompt:         "Please Enter the local destination to store the repo"
      default:        /tmp/3scaletmp
      private:        no
    - name:           amp_token
      prompt:         "Please Enter the 3SCale token that is required for 3Scale API calls. Defaults to a valid one in the DB"
      default:        c373d6c0262d307aaae51dc7a102f53ec32d8f642f88a97687c8dfabac15d838
      private:        no
    - name:           gogs_user
      prompt:         Gogs user name that you will create at registration
      default:        pprosser
      private:        no
#  vars:
#    DOMAIN_NAME_SUFFIX: apps.demolab.local
#    KEYSTORE_PASSWORD: test

  tasks:
    - name: Clone base git repo from "{{git_repo}}"
      git:
        repo: "{{git_repo}}"
        dest: "{{clone_destination}}/3Scale"
        update: yes
        clone: yes
# Login to Openshift using oc client - I can't get the openshift_raw module to authenticate
    - name:           login to Openshift at the specified URL
      shell:          oc login {{ocp_url}} --username={{ocp_username}} --password={{ocp_password}}

#####################################################
# Create project to deploy 3Scale Management Platform
#####################################################
    - name:           Create 3Scale AMP project
      openshift_raw:
        host:         "{{ocp_url}}"
        username:     "{{ocp_username}}"
        password:     "{{ocp_password}}"
        api_version:  v1
        verify_ssl:   no
        kind:         Project
        name:         amp
        description:  3Scale API Management Platform
        display_name: "3Scale API Management Platform"
        state:        present

#####################################################
# Create all AMP from template
#####################################################

    - name: Create new 3Scale AMP from template
      shell: oc new-app -n amp --file /{{clone_destination}}/3Scale/33scalebackup/amptemplates/amp.yml --param WILDCARD_DOMAIN={{domain_name_suffix}}

# Wait for 3Scale to start before continuing
    - name: Is 3Scale started?
      uri:
        validate_certs: no
        url: https://3scale-admin.{{domain_name_suffix}}/p/login
      register: test
      until: test.status == 200
      retries: 200
      delay: 5

# Capture pods names that need files injecting to recover 3SCale Correctly

    - name: Get OCP bearer token for API call
      shell: oc whoami -t
      register: ocptoken

    - name: Get mysql Pod
      uri:
        validate_certs: no
        url: "{{ocp_url}}/api/v1/namespaces/amp/pods?labelSelector=name=system-mysql"
        headers:
          Authorization: "Bearer {{ocptoken.stdout}}"
      register: mysql_pod

    - name: Capture mysql pod name
      set_fact:
        mysql_container: "{{mysql_pod|json_query('json.items[0].metadata.name')}}"

    - name: Get backend_redis pod
      uri:
        validate_certs: no
        url: "{{ocp_url}}/api/v1/namespaces/amp/pods?labelSelector=name=backend-redis"
        headers:
          Authorization: "Bearer {{ocptoken.stdout}}"
      register: backend_redis_pod

    - name: Capture backend_redis_pod pod name
      set_fact:
        backend_redis_container: "{{backend_redis_pod|json_query('json.items[0].metadata.name')}}"

    - name: Get system_redis pod
      uri:
        validate_certs: no
        url: "{{ocp_url}}/api/v1/namespaces/amp/pods?labelSelector=name=system-redis"
        headers:
          Authorization: "Bearer {{ocptoken.stdout}}"
      register: system_redis_pod

    - name: Capture backend_redis_pod pod name
      set_fact:
        system_redis_container: "{{system_redis_pod|json_query('json.items[0].metadata.name')}}"

# Copy the mysql backup file into the mysql container
    - name: "Inject mysql backup into container {{mysql_container}}"
      shell: oc rsync {{clone_destination}}/3Scale/3Scale_backup/db_archive_dir {{mysql_container}}:/var/lib/mysql/data -n amp

# execute
    - name: "Loading data into mysql"
      shell: oc exec {{mysql_container}} -n amp -- bash -c "mysql -u root < /var/lib/mysql/data/db_archive_dir/all.sql"

# load backend_redis cache

    - name: "Inject backend_redis cache backup into container {{backend_redis_container}}"
      shell: oc rsync {{clone_destination}}/3Scale/3Scale_backup/backend_redis/data {{backend_redis_container}}:/var/lib/redis -n amp

    - name: "restart backend_redis_container {{backend_redis_container}}"
      shell: oc delete pod {{backend_redis_container}} -n amp

# load system_redis cache

    - name: "Inject system_redis cache backup into container {{system_redis_container}}"
      shell: oc rsync {{clone_destination}}/3Scale/3Scale_backup/system_redis/data {{system_redis_container}}:/var/lib/redis -n amp

    - name: "restart backend_redis_container {{system_redis_container}}"
      shell: oc delete pod {{system_redis_container}} -n amp

    # Pause to make sure that 3Scale has fully revoverd from redis caches backups being installed

    # A helpful reminder of what to look out for post-update.
    - pause:
      prompt: "Has the Redis caches fully recovered?"

# Logout of Openshift
    - name:           logout of Openshift
      shell:          oc logout
