---
# Documentation:
# This playbook is used to deploy 3Scale, and a restful service
#
- name:               Create 3Scale AMP and deploy members api
  hosts:              localhost
  connection:         local
  gather_facts: no

  vars_prompt:
    - name:           ocp_username
      prompt:         "Please provide Openshift Login username"
      default:        developer
      private:        no
    - name:           ocp_password
      prompt:         "Please provide your Openshift Login password"
      default:        developer
      private:        yes
    - name:           ocp_url
      prompt:         "Please provide your Openshift URL"
      default:        https://192.168.99.100:8443
      private:        no
    - name:           domain_name_suffix
      prompt:         "Please Enter the domain wildcard name suffix for all OCP routes"
      default:        apps.demolab.local
      private:        no
    - name:           keystore_password
      prompt:         "Please enter the default password for keystores"
      default:        redhat123
    - name:           git_repo
      prompt:         "Please Enter the Git repo to clone to get hold of artefacts"
      default:        https://github.com/pprosser-redhat/3scalebackup.git
      private:        no
    - name:           clone_destination
      prompt:         "Please Enter the local destination to store the repo"
      default:        /tmp/3scaletmp
      private:        no
    - name:           amp_token
      prompt:         "Please Enter the 3SCale token that is required for 3Scale API calls. Defaults to a valid one in the DB"
      default:        c373d6c0262d307aaae51dc7a102f53ec32d8f642f88a97687c8dfabac15d838
      private:        no
    - name:           gogs_user
      prompt:         Gogs user name that you will create at registration
      default:        pprosser
      private:        no
#  vars:
#    DOMAIN_NAME_SUFFIX: apps.demolab.local
#    KEYSTORE_PASSWORD: test

  tasks:
    - name: Clone base git repo from "{{git_repo}}"
      git:
        repo: "{{git_repo}}"
        dest: "{{clone_destination}}/3Scale"
        update: yes
        clone: yes
# Login to Openshift using oc client - I can't get the openshift_raw module to authenticate
    - name:           login to Openshift at the specified URL
      shell:          oc login {{ocp_url}} --username={{ocp_username}} --password={{ocp_password}}

###################################################
# Create the fis demo project and application
#####################################################
    - name: Create fisdemo
      openshift_raw:
        host:         "{{ocp_url}}"
        username:     "{{ocp_username}}"
        password:     "{{ocp_password}}"
        api_version:  v1
        verify_ssl:   no
        kind:         Project
        name:         fisdemo
        description:  Development and UAT environment for Agile Integration Banking Demo - Power by Red Hat Fuse
        display_name: "Fuse Banking Demo - Dev and UAT"
        state:        present

    - name: Create fisdemo apicast secrets
      openshift_raw:
        host:           "{{ocp_url}}"
        username:       "{{ocp_username}}"
        password:       "{{ocp_password}}"
        namespace:      "fisdemo"
        definition: "{{ lookup('file', '{{clone_destination}}/3Scale/FuseBankingDevAndUat/ansible_definitions/secret-apicast.yaml') | from_yaml }}"
        state: present

    - name: Create fisdemo mysql secrets
      openshift_raw:
        host:           "{{ocp_url}}"
        username:       "{{ocp_username}}"
        password:       "{{ocp_password}}"
        namespace:      "fisdemo"
        definition: "{{ lookup('file', '{{clone_destination}}/3Scale/FuseBankingDevAndUat/ansible_definitions/secret-mysql.yaml') | from_yaml }}"
        state: present

    - name: Create fisdemo app
      shell: oc new-app --file {{clone_destination}}/3Scale/FuseBankingDevAndUat/project.yaml -n fisdemo -p MAVEN_MIRROR_URL=http://nexus-sharedservices.{{domain_name_suffix}}/repository/maven-all-public -p DOMAIN_NAME_SUFFIX={{domain_name_suffix}}

# Logout of Openshift
    - name:           logout of Openshift
      shell:          oc logout
