---
#file: main.yml
- name: Get OCP bearer token for API call
  shell: oc whoami -t
  register: ocptoken_sso

- name: Get SSO mysql Pod
  uri:
    validate_certs: no
    url: "{{ocp_url}}/api/v1/namespaces/sso/pods?labelSelector=deploymentconfig=sso-mysql"
    headers:
      Authorization: "Bearer {{ocptoken_sso.stdout}}"
  register: ssomysql_pod

- name: Capture ssomysql pod name
  set_fact:
    ssomysql_container: "{{ssomysql_pod|json_query('json.items[0].metadata.name')}}"

- name: "Inject sso mysql backup into container {{ssomysql_container}}"
  shell: oc rsync {{clone_destination}}/3Scale/3Scale_backup/sso/db_archive_dir {{ssomysql_container}}:/var/lib/mysql/data -n sso

- name: "Loading data into mysql"
  shell: oc exec {{ssomysql_container}} -n sso -- bash -c "mysql -u root < /var/lib/mysql/data/db_archive_dir/all.sql"