---
apiVersion: v1
groupNames:
- system:serviceaccounts:fisdemocicd
kind: RoleBinding
metadata:
  name: edit
  namespace: fisdemo
  selfLink: /oapi/v1/namespaces/fisdemo/rolebindings/edit
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: default
  namespace: fisdemo
#- kind: SystemGroup
#  name: system:serviceaccounts:fisdemocicd
- kind: ServiceAccount
  name: jenkins
  namespace: fisdemocicd
- kind: User
  name: mmusaji
userNames:
- system:serviceaccount:fisdemo:default
- system:serviceaccount:fisdemocicd:jenkins
- mmusaji
