---
apiVersion: v1
data:
  password: aHR0cHM6Ly9lNWJmODIzM2ZhYmZiM2EwMWRlYTY1NTcyMjRiNTU3OTY3NWVjM2Y3ZTdhM2M2ZTM2YmIwZjllNDVmNjAzMTQ4QHJlZC1oYXQtcGhpbHByb3NzZXItYWRtaW4uM3NjYWxlLm5ldA==
kind: Secret
metadata:
  name: apicast-configuration-url-secret
  namespace: fisdemo
  selfLink: /api/v1/namespaces/fisdemo/secrets/apicast-configuration-url-secret
type: kubernetes.io/basic-auth
