---
apiVersion: v1
items:
- apiVersion: v1
  data:
    password: aHR0cHM6Ly9lNWJmODIzM2ZhYmZiM2EwMWRlYTY1NTcyMjRiNTU3OTY3NWVjM2Y3ZTdhM2M2ZTM2YmIwZjllNDVmNjAzMTQ4QHJlZC1oYXQtcGhpbHByb3NzZXItYWRtaW4uM3NjYWxlLm5ldA==
  kind: Secret
  metadata:
    creationTimestamp: 2018-02-09T14:44:27Z
    name: apicast-configuration-url-secret
    namespace: fisdemo
    resourceVersion: "270371064"
    selfLink: /api/v1/namespaces/fisdemo/secrets/apicast-configuration-url-secret
    uid: bab87dd5-0da7-11e8-91ce-52540064f8a5
  type: kubernetes.io/basic-auth
- apiVersion: v1
  data:
    database-name: c2FtcGxlZGI=
    database-password: cGFzc3dvcmQ=
    database-root-password: cVNBazFUdlJHUE5LaFhjdA==
    database-user: ZGJ1c2Vy
  kind: Secret
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      template.openshift.io/expose-database_name: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    creationTimestamp: 2018-02-07T15:37:08Z
    labels:
      app: mysql-ephemeral
      template: mysql-ephemeral-template
    name: mysql
    namespace: fisdemo
    resourceVersion: "260363660"
    selfLink: /api/v1/namespaces/fisdemo/secrets/mysql
    uid: c21854fd-0c1c-11e8-8448-52540064f8a5
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
