---
apiVersion: v1
data:
  database-name: c2FtcGxlZGI=
  database-password: cGFzc3dvcmQ=
  database-root-password: cVNBazFUdlJHUE5LaFhjdA==
  database-user: ZGJ1c2Vy
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: mysql-ephemeral
    template: mysql-ephemeral-template
  name: mysql
  namespace: fisdemo
  selfLink: /api/v1/namespaces/fisdemo/secrets/mysql
type: Opaque
