apiVersion: v1
items:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-01T14:29:38Z
    name: admin
    namespace: amp
    resourceVersion: "242404823"
    selfLink: /oapi/v1/namespaces/amp/rolebindings/admin
    uid: 5580cc3c-075c-11e8-b959-52540064f8a5
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: pprosser
  userNames:
  - pprosser
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-01T14:29:38Z
    name: system:deployers
    namespace: amp
    resourceVersion: "242404817"
    selfLink: /oapi/v1/namespaces/amp/rolebindings/system%3Adeployers
    uid: 55804bcd-075c-11e8-b959-52540064f8a5
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: amp
  userNames:
  - system:serviceaccount:amp:deployer
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-01T14:29:38Z
    name: system:image-builders
    namespace: amp
    resourceVersion: "242404816"
    selfLink: /oapi/v1/namespaces/amp/rolebindings/system%3Aimage-builders
    uid: 557fd424-075c-11e8-b959-52540064f8a5
  roleRef:
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: amp
  userNames:
  - system:serviceaccount:amp:builder
- apiVersion: v1
  groupNames:
  - system:serviceaccounts:amp
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-02-01T14:29:38Z
    name: system:image-pullers
    namespace: amp
    resourceVersion: "242404815"
    selfLink: /oapi/v1/namespaces/amp/rolebindings/system%3Aimage-pullers
    uid: 557f2d24-075c-11e8-b959-52540064f8a5
  roleRef:
    name: system:image-puller
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:amp
  userNames: null
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
