apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: project.yaml
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: eap70-mysql-s2i
      application: eap-app
      template: eap70-mysql-s2i
      xpaas: 1.4.7
    name: eap-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: eap-app:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: v2
        uri: ${GIT_REPO}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
        - name: ARTIFACT_DIR
        forcePull: true
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.6
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: ams0jnkH
      type: GitHub
    - generic:
        secret: XlVTrFLx
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      app: eap70-basic-s2i
      application: eap-app70-v1
      template: eap70-basic-s2i
      xpaas: 1.4.7
    name: eap-app70-v1
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: eap-app70-v1:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: v1
        uri: ${GIT_REPO}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: MAVEN_MIRROR_URL
          value: ${MAVEN_MIRROR_URL}
        - name: ARTIFACT_DIR
        forcePull: true
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.6
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: KAfy3Csu
      type: GitHub
    - generic:
        secret: bjDIScma
      type: Generic
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: eap70-mysql-s2i
      application: eap-app
      template: eap70-mysql-s2i
      xpaas: 1.4.7
    name: eap-app
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry:5000/membersapp/eap-app:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: eap70-basic-s2i
      application: eap-app70-v1
      template: eap70-basic-s2i
      xpaas: 1.4.7
    name: eap-app70-v1
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry:5000/membersapp/eap-app70-v1:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: eap70-mysql-s2i
      application: eap-app
      template: eap70-mysql-s2i
      xpaas: 1.4.7
    name: eap-app
  spec:
    replicas: 1
    selector:
      deploymentConfig: eap-app
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: eap70-mysql-s2i
          application: eap-app
          deploymentConfig: eap-app
        name: eap-app
      spec:
        containers:
        - env:
          - name: DB_SERVICE_PREFIX_MAPPING
            value: eap-app-mysql=DB
          - name: DB_JNDI
            value: java:jboss/datasources/memberswebDS
          - name: DB_USERNAME
            value: userdAm
          - name: DB_PASSWORD
            value: cSAUac65
          - name: DB_DATABASE
            value: root
          - name: TX_DATABASE_PREFIX_MAPPING
            value: eap-app-mysql=DB
          - name: DB_MIN_POOL_SIZE
          - name: DB_MAX_POOL_SIZE
          - name: DB_TX_ISOLATION
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=eap-app
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: HTTPS_KEYSTORE_DIR
            value: /etc/eap-secret-volume
          - name: HTTPS_KEYSTORE
            value: keystore.jks
          - name: HTTPS_KEYSTORE_TYPE
          - name: HTTPS_NAME
          - name: HTTPS_PASSWORD
          - name: MQ_CLUSTER_PASSWORD
            value: HFVOP6JC
          - name: MQ_QUEUES
          - name: MQ_TOPICS
          - name: JGROUPS_ENCRYPT_SECRET
            value: eap7-app-secret
          - name: JGROUPS_ENCRYPT_KEYSTORE_DIR
            value: /etc/jgroups-encrypt-secret-volume
          - name: JGROUPS_ENCRYPT_KEYSTORE
            value: jgroups.jceks
          - name: JGROUPS_ENCRYPT_NAME
          - name: JGROUPS_ENCRYPT_PASSWORD
          - name: JGROUPS_CLUSTER_PASSWORD
            value: K6bAbAt1
          - name: AUTO_DEPLOY_EXPLODED
            value: "false"
          - name: DEFAULT_JOB_REPOSITORY
            value: eap-app-mysql
          - name: TIMER_SERVICE_DATA_STORE
            value: eap-app-mysql
          image: docker-registry.default.svc:5000/membersapp/eap-app@sha256:c9cbd40cac6ffd18b98271746b9adae5ff1e8428bfa24558802fd40b7b22550b
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/livenessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: eap-app
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8443
            name: https
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: eap7-service-account
        serviceAccountName: eap7-service-account
        terminationGracePeriodSeconds: 75
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - eap-app
        from:
          kind: ImageStreamTag
          name: eap-app:latest
          namespace: membersapp
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: eap70-mysql-s2i
      application: eap-app
      template: eap70-mysql-s2i
      xpaas: 1.4.7
    name: eap-app-mysql
  spec:
    replicas: 1
    selector:
      deploymentConfig: eap-app-mysql
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: eap70-mysql-s2i
          application: eap-app
          deploymentConfig: eap-app-mysql
        name: eap-app-mysql
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: userdAm
          - name: MYSQL_PASSWORD
            value: cSAUac65
          - name: MYSQL_DATABASE
            value: root
          - name: MYSQL_LOWER_CASE_TABLE_NAMES
          - name: MYSQL_MAX_CONNECTIONS
          - name: MYSQL_FT_MIN_WORD_LEN
          - name: MYSQL_FT_MAX_WORD_LEN
          - name: MYSQL_AIO
          image: registry.access.redhat.com/rhscl/mysql-57-rhel7@sha256:3abe773161b613b57f653c10ea1019ef7d9a05b2313390a8627be74df98dae77
          imagePullPolicy: Always
          name: eap-app-mysql
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 60
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - eap-app-mysql
        from:
          kind: ImageStreamTag
          name: mysql:5.7
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: eap70-basic-s2i
      application: eap-app70-v1
      template: eap70-basic-s2i
      xpaas: 1.4.7
    name: eap-app70-v1
  spec:
    replicas: 1
    selector:
      deploymentConfig: eap-app70-v1
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          application: eap-app70-v1
          deploymentConfig: eap-app70-v1
        name: eap-app70-v1
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=eap-app70-v1
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: MQ_CLUSTER_PASSWORD
            value: GQvST5A5
          - name: MQ_QUEUES
          - name: MQ_TOPICS
          - name: JGROUPS_CLUSTER_PASSWORD
            value: 3M5AJLWj
          - name: AUTO_DEPLOY_EXPLODED
            value: "false"
          - name: DB_SERVICE_PREFIX_MAPPING
            value: eap-app-mysql=DB
          - name: DB_JNDI
            value: java:jboss/datasources/memberswebDS
          - name: DB_USERNAME
            value: userdAm
          - name: DB_PASSWORD
            value: cSAUac65
          - name: DB_DATABASE
            value: root
          - name: TX_DATABASE_PREFIX_MAPPING
            value: eap-app-mysql=DB
          - name: DEFAULT_JOB_REPOSITORY
            value: eap-app-mysql
          - name: TIMER_SERVICE_DATA_STORE
            value: eap-app-mysql
          image: docker-registry:5000/membersapp/eap-app70-v1@sha256:ab326d1235fe5515ee8a53e78d252dc69c9d15af51b86f414035563af60014da
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/livenessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: eap-app70-v1
          ports:
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8888
            name: ping
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /opt/eap/bin/readinessProbe.sh
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 75
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - eap-app70-v1
        from:
          kind: ImageStreamTag
          name: eap-app70-v1:latest
          namespace: membersapp
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: eap70-mysql-s2i
      application: eap-app
      template: eap70-mysql-s2i
      xpaas: 1.4.7
    name: eap-app
  spec:
    host: eap-app-membersapp.${DOMAIN_NAME_SUFFIX}
    path: /membersweb/rest/v2/
    to:
      kind: Service
      name: eap-app
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-01-19T17:30:23Z
        status: "True"
        type: Admitted
      host: eap-app-membersapp.${DOMAIN_NAME_SUFFIX}
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: eap70-basic-s2i
      application: eap-app70-v1
      template: eap70-basic-s2i
      xpaas: 1.4.7
    name: eap-app70-v1
  spec:
    host: eap-app-membersapp.${DOMAIN_NAME_SUFFIX}
    to:
      kind: Service
      name: eap-app70-v1
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-02-21T18:41:20Z
        status: "True"
        type: Admitted
      host: eap-app-membersapp.${DOMAIN_NAME_SUFFIX}
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for application's https service.
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: eap70-mysql-s2i
      application: eap-app
      template: eap70-mysql-s2i
      xpaas: 1.4.7
    name: secure-eap-app
  spec:
    host: secure-eap-app-membersapp.${DOMAIN_NAME_SUFFIX}
    tls:
      termination: passthrough
    to:
      kind: Service
      name: secure-eap-app
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-01-19T17:30:23Z
        status: "True"
        type: Admitted
      host: secure-eap-app-membersapp.${DOMAIN_NAME_SUFFIX}
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
      openshift.io/generated-by: OpenShiftNewApp
      service.alpha.openshift.io/dependencies: '[{"name": "eap-app-mysql", "kind":
        "Service"}]'
    creationTimestamp: null
    labels:
      app: eap70-mysql-s2i
      application: eap-app
      template: eap70-mysql-s2i
      xpaas: 1.4.7
    name: eap-app
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentConfig: eap-app
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The database server's port.
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: eap70-mysql-s2i
      application: eap-app
      template: eap70-mysql-s2i
      xpaas: 1.4.7
    name: eap-app-mysql
  spec:
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      deploymentConfig: eap-app-mysql
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    creationTimestamp: null
    labels:
      app: eap70-basic-s2i
      application: eap-app70-v1
      template: eap70-basic-s2i
      xpaas: 1.4.7
    name: eap-app70-v1
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentConfig: eap-app70-v1
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      gluster.kubernetes.io/provisioned-for-pvc: membersdata
    name: glusterfs-dynamic-membersdata
  spec:
    ports:
    - port: 1
      protocol: TCP
      targetPort: 1
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's https port.
      openshift.io/generated-by: OpenShiftNewApp
      service.alpha.openshift.io/dependencies: '[{"name": "eap-app-mysql", "kind":
        "Service"}]'
    creationTimestamp: null
    labels:
      app: eap70-mysql-s2i
      application: eap-app
      template: eap70-mysql-s2i
      xpaas: 1.4.7
    name: secure-eap-app
  spec:
    ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deploymentConfig: eap-app
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
  - description: The URL of the repository with your application source code.
    displayName: Git Repository URL
    name: GIT_REPO
    required: true
    value: 'https://github.com/pprosser-redhat/members.git'
  - description: MAVEN_MIRROR_URL
    displayName: MAVEN_MIRROR_URL
    name: MAVEN_MIRROR_URL
    required: false
    value: http://nexus2-sharedservicespersistent.apps.demolab.local/content/groups/public/
  - description: Domain name suffix - added to all routes
    displayName: Domain Name Suffix
    name: DOMAIN_NAME_SUFFIX
    value: apps.demolab.local
