apiVersion: v1
items:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: 2018-01-19T17:43:04Z
    name: view
    namespace: membersapp
    selfLink: /oapi/v1/namespaces/membersapp/rolebindings/view
    uid: 33f5f0a4-fd40-11e7-8624-52540064f8a5
  roleRef:
    name: view
  subjects:
  - kind: ServiceAccount
    name: eap-service-account
    namespace: membersapp
  - kind: ServiceAccount
    name: eap7-service-account
    namespace: membersapp
  userNames:
  - system:serviceaccount:membersapp:eap-service-account
  - system:serviceaccount:membersapp:eap7-service-account
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
